let langdata = {
    "languages": {
        "en": {
            "strings": {
                "about-head": "About Me",
                "projects-head": "Projects",
                "japanese-head": "Japanese",
                "guitar-head": "Guitar",
                "contact-head": "Resume",
                "lang-selector": "日本語",
                "main-desc": "Programmer, Translator, Guitarist",
                "about-text": "Hello! My name is Jacob Cuke and I'm a graduate of Computer Science from the University of Calgary. As a programmer I specialize in web development and database management, but I also speak Japanese and do translation work on the side!",
                "skillset-head": "Skill Set",
                "projects-text": "Below are some of the projects that I'm most proud of, and I feel best represent my abilities as a programmer.",
                "mysouko-title": "MySouko",
                "mysouko-desc": "A web application I built to keep track of all the Japanese books/TV shows/games etc. that I've completed or am currently working on. Visit the site ",
                "mysouko-link": "here!",
                "mysouko-1": "Made using the Django framework in Python",
                "mysouko-2": "Postgres SQL database",
                "mysouko-3": "File storage with AWS S3 bucket",
                "mysouko-4": "Site hosted using Heroku",
                "mysouko-5": "HTML/CSS/JavaScript",
                "mysouko-6": "Mobile-friendly",
                "chess-title": "Chess Game",
                "chess-desc-1": "A chess game built entirely using JavaScript.",
                "chess-desc-2": "Try it out ",
                "chess-link": "here!",
                "chess-1": "JavaScript",
                "chess-2": "Highlight potential moves",
                "chess-3": "Collision detection",
                "engine-title": "Game Engine",
                "engine-desc": "This is a prototype game engine that I built from scratch in order to practice C++ and the Entity-Component-System (ECS) paradigm.",
                "engine-1": "Advanced C++",
                "engine-2": "XML level map",
                "engine-3": "Collision detection",
                "engine-4": "Uses the new industry ECS paradigm",
                "portfolio-title": "This Site!",
                "portfolio-desc": "I built this site from the ground up as a place to introduce myself and showcase the projects I've worked on in both English and Japanese!",
                "portfolio-1": "HTML/CSS/JavaScript",
                "portfolio-2": "Mobile responsive",
                "portfolio-3": "Multi-language support using JSON",
                "japanese-text": "What started as just a hobby quickly turned into one of my greatest passions as I spent 4 years teaching myself Japanese to fluency. I've worked as an interpreter, given speeches and even taken courses at the university level in Japan.",
                "exchange-head": "Study Abroad",
                "exchange-text": "I spent a total of 9 months across two separate trips to Japan studying at Senshu University in Tokyo. While there I studied both Computer Science and Japanese culture, while also helping a local church with the translation and interpretation of their Sunday services.",
                "speech-head": "Speeches",
                "speech-text": "I also helped out my university by participating in events, where I gave multiple speeches and presentations entirely in Japanese to university, high school and elementary students.",
                "guitar-text": "I also taught myself to play the electric guitar, and currently play for one of the largest churches in Canada, Centre Street Church, where I have served for over 4 years.",
                "live-head": "Live Services",
                "live-text": "At CSC we have live services every weekend where I regularly serve in the worship band. This is one of the songs we did recently!",
                "mv-head": "Music Videos",
                "mv-text": "Here is one of the music videos we made for the Christmas season. Thankfully it wasn't very cold when we filmed it!",
                "contact-text": "Below is a link to my full resume and contact information. Feel free to reach out in whatever way works best.",
                "resume-button": "Download Resume",
                "school-title": "School Management System",
                "school-desc": "A complete web application and API that allows students and instructors to manage their courses, view lectures, submit and grade assignments.",
                "school-1": "Built with the Django framework",
                "school-2": "SQL database with 15+ related tables",
                "school-3": "Fully fleshed out API with authentication"
            }
        },
        "jp": {
            "strings": {
                "about-head": "自己紹介",
                "projects-head": "制作実績",
                "japanese-head": "日本語",
                "guitar-head": "ギター",
                "contact-head": "履歴書",
                "lang-selector": "English",
                "main-desc": "プログラマー／翻訳者／ギタリスト",
                "about-text": "初めまして！カナダのカルガリー大学コンピューターサイエンス学科卒業のジェイコブと申します。Webプログラミングとデータベース管理を専門とする、日本語が話せる日本が大好きなプログラマー兼日英翻訳者です！どうぞよろしくお願いします。",
                "skillset-head": "技術",
                "projects-text": "制作の中からもっとも自分のプログラミングの技量を代表するのに相応しいと思ったプロジェクトを三つ選び、以下に紹介します。",
                "mysouko-title": "My倉庫",
                "mysouko-desc": "今まで完成した日本語の小説やゲームを記録するために作ったウェブアプリケーションです。サイトは",
                "mysouko-link": "こちら！",
                "mysouko-1": "Pythonフレームワーク「Django」で作られた",
                "mysouko-2": "Postgres SQL データベース",
                "mysouko-3": "AWS S3のファイルストレージ",
                "mysouko-4": "「Heroku」の環境で実行されている",
                "mysouko-5": "HTML/CSS/JavaScript",
                "mysouko-6": "モバイルフレンドリー",
                "chess-title": "チェス",
                "chess-desc-1": "JavaScriptで作られたチェスゲーム。",
                "chess-desc-2": "リンクは",
                "chess-link": "こちら！",
                "chess-1": "JavaScript",
                "chess-2": "駒が動けるマスをハイライトする",
                "chess-3": "衝突判定",
                "engine-title": "ゲームエンジン",
                "engine-desc": "C++とEntity Component System (ECS)の設計を練習するためにゼロから作られたゲームエンジン。",
                "engine-1": "上級C++",
                "engine-2": "XMLマップ",
                "engine-3": "衝突判定",
                "engine-4": "ゲーム業界の最新設計(ECS)",
                "portfolio-title": "このサイト!",
                "portfolio-desc": "自分と今まで完成してきたプロジェクトを紹介するために作ったウェブサイト。英語も日本語もあります！",
                "portfolio-1": "HTML/CSS/JavaScript",
                "portfolio-2": "モバイルフレンドリー",
                "portfolio-3": "JSONを通して英語も日本語あり",
                "japanese-text": "趣味で始めたことがここまで大切で大好きなことになってくるとは４年前に思いもしませんでした。暇があればひたすら勉強に勤しみ、通訳者の仕事、スピーチにプレゼンテーション、そして日本の大学での正規授業といった経験を通し、生活や仕事に支障と不自由がない程成長することができました。",
                "exchange-head": "留学",
                "exchange-text": "２回の留学交換にわたって神奈川県の専修大学で9ヶ月間勉強しました。専大で正規の授業を取らせていただき、コンピューターサイエンスと日本の文化を日本語で勉強することができました。大学の勉強以外にも、通っていた教会の日英翻訳や通訳をやらせていただきました。",
                "speech-head": "スピーチ",
                "speech-text": "大学の国際交流事務所のイベントにも協力し、大学生、高校生、そして小学生を対象にさまざまなスピーチやプレゼンテーションを日本語で行いました。",
                "guitar-text": "ギターの弾き方も独学で覚え、４年前からカナダの中で一番大きな教会でバンドのギターを担当させていただいています。以下の動画はライブ配信の演出、そしてクリスマスに撮影したMVからの映像です。",
                "live-head": "ライブ",
                "live-text": "毎週賛美という演出があり、それに頻繁に参加しています。この動画は最近の配信からのものなので、ご興味がある方は是非見てみてください！",
                "mv-head": "MV撮影",
                "mv-text": "そして次の動画はクリスマスのために特別に撮影したMVなのです。幸いにも撮影当日はそれほど寒くありませんでした！",
                "contact-text": "以下のリンクにて履歴書のPDF版をチェックすることができますので是非お目通し下さい。そして何かがありましたらメールなり何なり遠慮なくご連絡ください。ご覧いただきありがとうございます！",
                "resume-button": "履歴書をダウンロード",
                "school-title": "高校管理システム",
                "school-desc": "高校管理を行うためのウェブアプリおよそAPI。コースの管理や課題の提出・評価が可能。",
                "school-1": "Pythonフレームワーク「Django」で作成された",
                "school-2": "15以上のテーブルを含むSQLデータベース",
                "school-3": "認証付きのAPI"
            }
        }
    }
}
