let langdata = {
    "languages": {
        "en": {
            "strings": {
                "about-head": "About Me",
                "projects-head": "Projects",
                "japanese-head": "Japanese",
                "guitar-head": "Guitar",
                "contact-head": "Resume",
                "lang-selector": "日本語",
                "main-desc": "Programmer, Translator, Guitarist",
                "about-text": "Hello! My name is Jacob Cuke and I'm a graduate of Computer Science from the University of Calgary. As a programmer I specialize in web development and database management, but I also speak Japanese and do translation work on the side!",
                "skillset-head": "Skill Set",
                "projects-text": "Below are some of the projects that I'm most proud of, and I feel best represent my abilities as a programmer.",
                "mysouko-title": "MySouko",
                "mysouko-desc": "A web application I built to keep track of all the Japanese books/TV shows/games etc. that I've completed or am currently working on. Visit the site ",
                "mysouko-link": "here!",
                "mysouko-1": "Made using the Django framework in Python",
                "mysouko-2": "Postgres SQL database",
                "mysouko-3": "File storage with AWS S3 bucket",
                "mysouko-4": "Site hosted using Heroku",
                "mysouko-5": "HTML/CSS/JavaScript",
                "mysouko-6": "Mobile-friendly",
                "chess-title": "Chess Game",
                "chess-desc-1": "A chess game built entirely using JavaScript.",
                "chess-link": "Try it here!",
                "chess-1": "JavaScript",
                "chess-2": "Highlight potential moves",
                "chess-3": "Collision detection",
                "engine-title": "Game Engine",
                "engine-desc": "This is a prototype game engine that I built from scratch in order to practice C++ and the Entity-Component-System (ECS) paradigm.",
                "engine-1": "Advanced C++",
                "engine-2": "XML level maps",
                "engine-3": "Collision detection",
                "engine-4": "Uses the new industry ECS paradigm",
                "portfolio-title": "Portfolio Website",
                "portfolio-desc": "I built this site from the ground up as a place to introduce myself and showcase the projects I've worked on in both English and Japanese!",
                "portfolio-1": "HTML/CSS/JavaScript",
                "portfolio-2": "Mobile responsive",
                "portfolio-3": "Multi-language support using JSON",
                "japanese-text": "What started as just a hobby quickly turned into one of my greatest passions as I spent 5 years teaching myself Japanese to fluency. I've worked as an interpreter, given speeches and even taken courses at the university level in Japan.",
                "exchange-head": "Study Abroad",
                "exchange-text": "I spent a total of 9 months across two separate trips to Japan studying at Senshu University in Tokyo. While there I studied both Computer Science and Japanese culture, while also helping a local church with the translation and interpretation of their Sunday services.",
                "speech-head": "Speeches",
                "speech-text": "I also helped out my university by participating in events, where I gave multiple speeches and presentations entirely in Japanese to university, high school and elementary students.",
                "guitar-text": "I also taught myself to play the electric guitar, and currently play for one of the largest churches in Canada, Centre Street Church, where I have served for over 5 years.",
                "live-head": "Live Services",
                "live-text": "At CSC we have live services every weekend where I regularly serve in the worship band. This is one of the songs we did recently!",
                "mv-head": "Music Videos",
                "mv-text": "Here is one of the music videos we made for the Christmas season. Thankfully it wasn't very cold when we filmed it!",
                "contact-text": "Below is a link to my full resume and contact information. Feel free to reach out in whatever way works best.",
                "resume-button": "Download Resume",
                "school-title": "School Management System",
                "school-desc": "A complete web application and API that allows students and instructors to manage their courses, view lectures, submit and grade assignments. Visit the site ",
                "school-link": "here!",
                "school-1": "Built with the Django framework",
                "school-2": "SQL database with 15+ related tables",
                "school-3": "Fully fleshed out API with authentication"
            }
        },
        "jp": {
            "strings": {
                "about-head": "自己紹介",
                "projects-head": "制作実績",
                "japanese-head": "日本語",
                "guitar-head": "ギター",
                "contact-head": "履歴書",
                "lang-selector": "English",
                "main-desc": "プログラマー／ウェブディベロッパー",
                "about-text": "カナダ国内大学の10位内に入るカルガリー大学でコンピューターサイエンスを学んだのち、ウェブディベロッパーの仕事に就きました。バックエンドやデータベース管理を専門としていますが、仕事及び個人的のプロジェクトでフロントエンドにも携わっています。大学時代に日本に興味を持ったのをきっかけに独学で日本語を覚え、今は日本で活動することを目指しています。",
                "skillset-head": "技術",
                "projects-text": "最も熱と力を入れた制作を紹介します。経験こそ少なめなのは認識していますが、更なる成長を常に求め、新しい技術を積極的に習得していくという私の強みが表されていると思います。",
                "mysouko-title": "My倉庫",
                "mysouko-desc": "小説、アニメ、ゲーム等、日本語能力を上げるために楽しんできたものを記録するウェブアプリケーションです。",
                "mysouko-link": "こちらをご覧ください。",
                "mysouko-1": "PythonのDjangoフレームワークで作成しました",
                "mysouko-2": "PostgreSQLのデータベース",
                "mysouko-3": "AWS S3のファイルストレージ",
                "mysouko-4": "Herokuのサーバーにて配置されています",
                "mysouko-5": "HTML/CSS/JavaScript",
                "mysouko-6": "モバイルフレンドリー",
                "chess-title": "チェス",
                "chess-desc-1": "HTML・CSS・JavaScriptのみで仕上げられたチェスゲーム。",
                "chess-link": "誰かと勝負してみてください。",
                "chess-1": "HTML/CSS/JavaScript",
                "chess-2": "移動可能のマスが計算してハイライトされます",
                "chess-3": "衝突判定",
                "engine-title": "ゲームエンジン",
                "engine-desc": "C++とEntity Component System (ECS)のパラダイムをより深く理解するためにゼロから作ってみたゲームエンジン。",
                "engine-1": "C++の上級技術",
                "engine-2": "XMLを使用したマップ",
                "engine-3": "衝突判定",
                "engine-4": "ゲーム業界の最新設計(ECS)",
                "portfolio-title": "ポートフォリオサイト",
                "portfolio-desc": "今まで作成してきたプロジェクト、あるいはプライベートでやり遂げたことなどを紹介するウェブサイト。英語にも日本語にも書かれています。",
                "portfolio-1": "HTML/CSS/JavaScript",
                "portfolio-2": "モバイルフレンドリー",
                "portfolio-3": "言語設定",
                "japanese-text": "大学に入る直前に日本に興味を持ち、5年間にわたる猛勉強の成果として日本語を話せるように、読めるように、そして書けるようになりました。日本への留学を経てその愛が深まり、日本語を聞いたり読んだりしない日が一日たりともないほど非常に大切なことです。毎日こつこつと日本語力を上げながら、日本での就職を目指しています。",
                "exchange-head": "留学",
                "exchange-text": "２度の留学にわたって神奈川県の専修大学で9ヶ月を過ごしました。日本人と一緒に正規授業に参加させていただき、プログラミングの面でも日本語の面でも貴重な体験になりました。課外活動でスピーチや通翻訳をする機会もたくさんいただいておりました。",
                "speech-head": "スピーチ",
                "speech-text": "大学の国際交流事務所のイベントに協力し、大学生、高校生、小学生までを対象にさまざまなスピーチやプレゼンテーションを日本語で行ってきました。",
                "guitar-text": "趣味のギターも紹介したいと思います。ギタリストとしての活躍に興味がありましたら是非以下の動画や個人のインスタをチェックしてみてください。",
                "live-head": "ライブ",
                "live-text": "500人以上の人が集まる会場で演出しています",
                "mv-head": "MV撮影",
                "mv-text": "プライベートでもこつこつと練習しながら楽しんでいます。",
                "contact-text": "最後までご覧いただきありがとうございます。以下のリンクにて履歴書のPDF版がダウンロードできますので是非お目通し下さい。そして私に何かのコメントやフィードバックなどがありましたらメールなり何なりで遠慮なくご連絡ください。",
                "resume-button": "履歴書をダウンロード",
                "school-title": "高校管理システム",
                "school-desc": "高校管理をより効率的に行うためのウェブアプリケーションとAPI。授業の管理や課題の提出・評価が可能です。バックエンド開発とデータベース管理への愛から生まれた制作です。",
                "school-link": "こちらをご覧ください。",
                "school-1": "PythonのDjangoフレームワークで作成しました",
                "school-2": "15以上のテーブルを含むSQLデータベース",
                "school-3": "認証付きのAPI"
            }
        }
    }
}
